spring.application.name=API PARA UM ECOME

spring.datasource.username = comercio

spring.datasource.password = comercio

spring.datasource.url = jdbc:postgresql://localhost:5432/db_comercio?useTimezone=true&serverTimezone=UTC

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show_sql = true

